server.default_listen_address=0.0.0.0

server.memory.pagecache.size=512M
dbms.memory.transaction.total.max=2G
server.memory.heap.max_size=1G
server.databases.default_to_read_only=false
dbms.security.procedures.unrestricted=apoc.*,n10s.*
dbms.security.procedures.allowlist=apoc.*,n10s.*
server.directories.plugins=/plugins
server.directories.logs=/logs
